17-2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -51,3 +51,8 @@ jobs:
             docker stop app || true
             docker rm app || true
             docker run -d -p 8000:8000 --name app 983915441388.dkr.ecr.us-east-1.amazonaws.com/ci_ecr:latest
+      - name: Health check
+        run: |
+          echo "Waiting for app to start..."
+          sleep 15
+          curl -f <http://18.212.223.57:8000/ || (echo "Health check failed!" && exit 1)
