17-2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -55,4 +55,4 @@ jobs:
         run: |
           echo "Waiting for app to start..."
           sleep 15
-          curl -f <http://18.212.223.57:8000/ || (echo "Health check failed!" && exit 1)
+          curl -f http://18.205.17.255:8000 || (echo "Health check failed!" && exit 1)
